[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
foldhash = "0.2.0"
itertools = "0.14.0"
nom = "8.0.0"
rstest = "0.26.1"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
